// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKs0szVNOVyz_i_MrhpQhk7cJArViCSQg',
    appId: '1:644293206988:web:4966232ac46e5cdb3b3369',
    messagingSenderId: '644293206988',
    projectId: 'rablo-chat',
    authDomain: 'rablo-chat.firebaseapp.com',
    storageBucket: 'rablo-chat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZs7TTHKlFdyvAPdB4A9KziYnFkn30ZF8',
    appId: '1:644293206988:android:8ccfa87b50d977f83b3369',
    messagingSenderId: '644293206988',
    projectId: 'rablo-chat',
    storageBucket: 'rablo-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuNdFH6Slxfcp5ISH6qGy3YR5rBazlP4k',
    appId: '1:644293206988:ios:7d7385673fde940e3b3369',
    messagingSenderId: '644293206988',
    projectId: 'rablo-chat',
    storageBucket: 'rablo-chat.firebasestorage.app',
    iosBundleId: 'com.example.rabloChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuNdFH6Slxfcp5ISH6qGy3YR5rBazlP4k',
    appId: '1:644293206988:ios:7d7385673fde940e3b3369',
    messagingSenderId: '644293206988',
    projectId: 'rablo-chat',
    storageBucket: 'rablo-chat.firebasestorage.app',
    iosBundleId: 'com.example.rabloChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKs0szVNOVyz_i_MrhpQhk7cJArViCSQg',
    appId: '1:644293206988:web:6050347550415e853b3369',
    messagingSenderId: '644293206988',
    projectId: 'rablo-chat',
    authDomain: 'rablo-chat.firebaseapp.com',
    storageBucket: 'rablo-chat.firebasestorage.app',
  );
}
